<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>AT.Automation.Desktop</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\AT.Core\AT.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="FlaUI.Core" Version="4.0.0" />
		<PackageReference Include="FlaUI.UIA3" Version="4.0.0" />
	</ItemGroup>

</Project>