<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>AT.Automation.Web</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AT.Core\AT.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Selenium.WebDriver" Version="4.29.0" />
    <PackageReference Include="Selenium.Support" Version="4.29.0" />
  </ItemGroup>

</Project>
